name: Deploy via SFTP to Hostinger

on:
  push:
    branches: [ "public_html" ]     # ggf. "main", je nachdem, von wo du deployst
  workflow_dispatch: {}

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Remove unnecessary files before deploy
        run: |
          rm -rf .git
          rm -rf .github
          rm -rf node_modules
          find . -name "*.map" -type f -delete
          find . -name ".DS_Store" -type f -delete

      - name: Deploy to Hostinger via SFTP
        uses: wlixcc/SFTP-Deploy-Action@v1.2.4
        with:
          server: ${{ secrets.HOST }}
          port: ${{ secrets.PORT }}
          username: ${{ secrets.USER }}
          ssh_private_key: ${{ secrets.SSH_PRIVATE_KEY }}
          local_path: "./"   # <-- nutzt jetzt dein gesamtes Repo
          remote_path: "domains/firebrick-squirrel-568721.hostingersite.com/public_html/"
          sftp_only: true
          delete_remote_files: false
